version: '3'
services:
  duckdns:
    build: ./duckdns
    env_file: duckdns.env
    restart: always
  cloudflare-dns:
    build: ./cloudflare-dns-server
    command: -vvv
    ports:
      - 53:53/udp
    network_mode: bridge
    restart: always
  openvpn:
    cap_add:
     - NET_ADMIN
    build: ./docker-openvpn
    ports:
     - 1194:1194/udp
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn

