#!/bin/bash

${DUCKDNS_DOMAIN:?"Need to set target domain to update dns entry for"}
${DUCKDNS_TOKEN:?"Need to set authentication token"}

LOG_FILE=/var/log/duckdns.log

now=$(date)
url="https://www.duckdns.org/update?domains=$DUCKDNS_DOMAIN&token=$DUCKDNS_TOKEN&ip="

echo "Updating dns entry at: $now" >> $LOG_FILE
echo "GET $url" >> $LOG_FILE

echo url="$url" | curl -s -o /dev/null -w "%{http_code}" --config - >> $LOG_FILE 2>&1
